name: nglview-gha

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - pip
  - jupyter-packaging
  - qcelemental
  - traitlets
  - ipywidgets>=8.0.5
  - comm>=0.1.3  # see https://github.com/jupyter-widgets/ipywidgets/issues/3729
  - ipykernel
  - notebook
  - mock
  - coverage
  - nose
  - pytest
  - pytest-cov
  - coveralls
  - pandas
  - ase
  - biopython
  - pymatgen
  - simpletraj
  - matplotlib
  - moviepy
  - imageio
  - pillow
  - numpy
  - rdkit
  - mdanalysis
  - mdtraj
  - parmed
  - ambertools
