name: nglview-gha

channels:
  - conda-forge

dependencies:
  - jupyter-packaging
  - qcelemental
  - traitlets
  - ipywidgets>=8.0.5
  - comm>=0.1.3  # see https://github.com/jupyter-widgets/ipywidgets/issues/3729
  - ipykernel
  - notebook
  - coverage
  - pytest
  - pytest-cov
  - pandas
  - ase
  - biopython
  - pymatgen
  - matplotlib
  - moviepy
  - imageio
  - pillow<11.2.1
  - numpy
  - numpy<2.3.0
  - rdkit
  - mdanalysis
  - mdtraj
  - ambertools # have both pytraj and parmed
  - pip
