[build-system]
requires = ["jupyter_packaging>=0.7.9", "setuptools>=75.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
