#!/usr/bin/env python

import os, sys
import subprocess

if float(os.environ.get('PYTHON_VERSION')) >= 3.4 and sys.platform == 'linux':
    subprocess.check_call('coveralls')
else:
    print('only perform coverage reporting for Python version >= 3.4 on Linux')
